name: Terraform Tests, Docs & Compliance

on:
  workflow_call:
    inputs:
      module_dirs:
        required: true
        type: string
      tf_version:
        required: false
        type: string
        default: 1.1.0

jobs:
  tf-validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{fromJson(inputs.module_dirs)}}

    steps:
      - name: Checkout source code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform validation
        working-directory: ${{ matrix.dir }}
        run: |
          terraform init -reconfigure
          terraform fmt -recursive -check
          terraform validate

  tf-docs:
    name: Terraform documentation
    runs-on: ubuntu-latest
    needs: tf-validate
    strategy:
      matrix:
        dir: ${{fromJson(inputs.module_dirs)}}

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6 # v1.1.0
        with:
          working-dir: ${{ matrix.dir }}
          output-file: README.md
          output-method: inject
          git-push: "true"

  checkov-scan:
    name: Run policy scan
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{fromJson(inputs.module_dirs)}}

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ inputs.tf_version }}
          terraform_wrapper: false
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@d26020ae0b8dfdddfab43acf7fdcf3b1f7298246 # v12
        with:
          directory: ${{ matrix.dir }}
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,results.sarif
          download_external_modules: true
      - name: Upload Checkov SARIF results
        uses: github/codeql-action/upload-sarif@v3
        # upload results even if the action fails:
        if: success() || failure()
        with:
          sarif_file: results.sarif
