name: Terraform Tests, Docs & Compliance

on:
  workflow_call:
    inputs:
      module_dirs: 
        required: true
        type: string
      tf_version:
        required: false
        type: string
        default: 0.13.2

jobs:
  tf-validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dir: ${{fromJson(inputs.module_dirs)}}

    steps:
      - name: Checkout source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform validation
        working-directory: ${{ matrix.dir }}
        run: |
          terraform init -reconfigure
          terraform fmt -recursive -check
          terraform validate

  tf-docs:
    name: Terraform documentation
    runs-on: ubuntu-latest
    needs: tf-validate
    strategy:
      matrix: 
        dir: ${{fromJson(inputs.module_dirs)}}

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # renovate: tag=v1.0.0
        with:
          working-dir: ${{ matrix.dir }}
          output-file: README.md
          output-method: inject
          git-push: "true"
