name: Terraform Tests, Docs & Compliance

on:
  workflow_call:
    inputs:
      module_dirs: 
        required: true
        type: string
      tf_version:
        required: false
        type: string
        default: 0.13.2

jobs:
  tf-validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dir: ${{fromJson(inputs.module_dirs)}}

    steps:
      - name: Checkout source code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform validation
        working-directory: ${{ matrix.dir }}
        run: |
          terraform init -reconfigure
          terraform fmt -recursive -check
          terraform validate

  tf-docs:
    name: Terraform documentation
    runs-on: ubuntu-latest
    needs: tf-validate
    strategy:
      matrix: 
        dir: ${{fromJson(inputs.module_dirs)}}

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # renovate: tag=v1.0.0
        with:
          working-dir: ${{ matrix.dir }}
          output-file: README.md
          output-method: inject
          git-push: "true"
          
  checkov-scan:
    name: Run policy scan
    permissions:
      contents: 'read'
      security-events: 'write'
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dir: ${{fromJson(inputs.module_dirs)}}

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.0
          terraform_wrapper: false
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ matrix.dir }}
          log_level: DEBUG
          soft_fail: true
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,results.sarif
          download_external_modules: true
          skip_check: CKV_TF_1,CKV_GCP_97,CKV_GCP_114,CKV_GCP_62
          
      - name: Upload Checkov SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
