name: Release Please

on:
  workflow_call:
    inputs:
      version_bumped_files:
        required: false
        type: string
        default: README.md

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@0fef4afcc574a384e0d8cee69de13e864b80dc6f # v3.2.7
        with:
          release-type: terraform-module
          package-name: release-please-action
          extra-files: ${{ inputs.version_bumped_files }}
